<?php

namespace Jewome62\SfrByPass\ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DecodeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DecodeurRepository extends EntityRepository
{
}
